### ISSUE TITLE
minimum stem length in ReadWordFreqFile

### ISSUE THREAD

**Issue by anna-hope** [lxa2015/lxa-py#4]
What's the reason behind removing the minimum stem length argument from ReadWordFreq? I think we should keep it, even if as an optional argument because it's handy to be able to pre-filter the words when we build a corpus.

**Comment by jacksonllee** [comment]
I remember the relevant code inside ReadWordFreq had already been commented out and not used for a long while, and that's why when I saw this part (again) this week I decided to take it away together with the optional argument in order to avoid confusion. Filtering is definitely relevant, but if ReadWordFreq is what reads a corpus data file, then filtering shouldn't happen here at the outset and everything (including words shorter than min stem length) from the raw corpus should be kept. Two major reasons why we do this: (1) We have to keep track of the various statistics of raw and derived datasets; (2) different programs (lxa5 being just one of them -- many more will be brought into the picture) have different filtering requirements, and filtering should be done by the individual programs as appropriate but not globally at the very beginning.

**Comment by anna-hope** [comment]
Okay, I understand. Do you think it would also not be acceptable to keep the minimum stem length as an optional argument, the way it is in the stemalts branch: https://github.com/lxa2015/lxa-py/commit/7f6a776f1127ae22f1b07653982e73b016024e88?

**Comment by jacksonllee** [comment]
Implementationally, it shouldn't really be an issue if it's an optional argument (I took away what I thought to be the non-optional version of the code -- sorry if this is not the case!), and especially if you think the knowledge of a master wordlist with no filtering is not important in your case (though we often ask, say, how many word types or tokens you are dealing with---and other things before pre-filtering is applied---when examining the results).
